# Generated by Django 4.2.7 on 2025-07-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_menuitem_image_alter_specialmenu_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpecialMenu',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='ingredients',
            field=models.TextField(blank=True, help_text='List of ingredients used in the dish.', null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='made_by',
            field=models.CharField(blank=True, help_text='Chef or cook who made the dish.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='procedure',
            field=models.TextField(blank=True, help_text='Preparation procedure for the dish.', null=True),
        ),
        migrations.DeleteModel(
            name='TopSelling',
        ),
    ]
