# Generated by Django 4.2.7 on 2025-07-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_delete_specialmenu_menuitem_ingredients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_special',
            field=models.BooleanField(default=False, help_text='Is this a special menu item?'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_top_selling',
            field=models.BooleanField(default=False, help_text='Is this a top selling item?'),
        ),
    ]
