# Generated by Django 4.2.7 on 2025-07-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_remove_reservation_notes_reservation_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.TimeField(default='12:00'),
        ),
    ]
