# Generated by Django 4.2.7 on 2025-07-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_order_payment_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='progress',
            field=models.CharField(choices=[('received', 'Order Received'), ('preparing', 'Preparing'), ('ready', 'Ready for Pickup/Delivery'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='received', max_length=30),
        ),
    ]
