# Generated by Django 5.1.2 on 2025-09-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_event_heroslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('chef', 'Chef'), ('waiter', 'Waiter'), ('manager', 'Manager'), ('cashier', 'Cashier')], default='waiter', max_length=30),
        ),
    ]
